name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Clone submodules
      run: git submodule update --init --recursive

    # test in debug
    - name: Configure CMake [DEBUG]
      run: cmake -B ${{github.workspace}}/debug -DCMAKE_BUILD_TYPE=debug

    - name: Build
      run: cmake --build ${{github.workspace}}/debug --target test_pazusoba

    - name: Test
      working-directory: ${{github.workspace}}/debug
      run: ./test_pazusoba.out

    # test in release just in case
    - name: Configure CMake [RELEASE]
      run: cmake -B ${{github.workspace}}/release

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/release --target test_pazusoba

    - name: Test
      working-directory: ${{github.workspace}}/release
      run: ./test_pazusoba.out
