name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: => go to test/
      run: cd test/
    - name: => build for test
      run: g++ -Wall -Wextra -pedantic test.cpp -o pazusoba.test
    - name: => test pazusoba
      run: ./pazusoba.test
